### ISSUE TITLE
[FR] auto add "install" and "prune" for npm

### ISSUE THREAD

**Issue by farfromrefug** [lkytal/quickTask#1]
Thanks!

**Comment by lkytal** [comment]
This extension is intent to provide a convenient way to access you task defined in package.json (and gulp or so), so I'm wondering what do you mean by 'auto add "install" and "prune" for npm' ?

**Comment by farfromrefug** [comment]
Yes i mean "npm install" and "npm prune" which are default added npm tasks.
I think it could be very useful to have them too

**Comment by lkytal** [comment]
I'll considerate to provide an option to include "npm install" and "npm prune" in recent.

**Comment by farfromrefug** [comment]
@lkytal thanks that would be awesome!

**Comment by lkytal** [comment]
After consideration, I won't directly add those tasks, however, I provide an "defaultTask" option which you can add tasks you want. Please update to see.
