### ISSUE TITLE
Does not include gulpfile.babel.js gulp tasks

### ISSUE THREAD

**Issue by nealoke** [lkytal/quickTask#13]
Hi! Thanks for adding the folder the tasks are found, works great! I've found however that my tasks specified in `gulpfile.babel.js` are not picked up. :)

**Comment by lkytal** [comment]
Should support now.

**Comment by nealoke** [comment]
@lkytal working however the file path is not present for these files :D btw thank you for this awesome plugin!

![tasks](https://user-images.githubusercontent.com/17417414/29177587-5967992c-7def-11e7-9f74-194a4b9cdb5d.png)

**Comment by nealoke** [comment]
Might also be nice to have the matching icons for gulp tasks :) 🥇

**Comment by lkytal** [comment]
Regretfully VS Code currently don't have a builtin gulp icon....
