### ISSUE TITLE
Auto-detect tasks using VS Code Tasks 2.0

### ISSUE THREAD

**Issue by aefernandes** [lkytal/quickTask#14]
It would be great if your extension supported the auto-detected tasks in VS Code [Tasks 2.0](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection).

For example, in a project with a gruntfile containing one default watch task, the auto-detected tasks appear as follows:
![image](https://user-images.githubusercontent.com/7109548/29295039-2ece65ea-8107-11e7-8b66-3bead37f39b7.png)

while clicking the status bar icon shows:
![image](https://user-images.githubusercontent.com/7109548/29295030-256e32e6-8107-11e7-99db-33cdf195a9f1.png)

Maybe this support could be extended by registering new [task providers](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametaskprovideraspan-classcodeitem-id1143taskproviderspan) or perhaps something new can be proposed for the VS Code API.

**Comment by lkytal** [comment]
VS code hasn't exposed it's tasks API yet so I won't be able to make complete support currently.

**Comment by aefernandes** [comment]
No problem. I ran into something similar and opened #32352 in the Microsoft/vscode repo.
