### ISSUE TITLE
Automatically install NPM packages

### ISSUE THREAD

**Issue by edirpedro** [lkytal/quickTask#15]
Is there a reason to not install NPM packages automatically?

QuickTask should execute `npm install` if the folder `/node_modules` does not exist and the file `package.json` is available.

But instead, trying to execute `gulp watch`, it outputs `Local gulp not found. Try running: npm install gulp`. This is still the wrong command to indicate to the user, because it will only install Gulp and the tasks won't work after that. The right message should be `Try running: npm install`.

QuickTask could also check for updates in the package.json to make sure all the dependencies are local installed before running a task. And install it if not found.

**Comment by lkytal** [comment]
Actually I think those shouldn't be the task of this extension, the `QuickTask` is designed only for run your command and leave the management to other tools (lots of them as I know).
