### ISSUE TITLE
Path of task is removed?

### ISSUE THREAD

**Issue by nealoke** [lkytal/quickTask#20]
Hi, I have a monolithic repo (using `lerna`) which uses same task names such as `sever` or `build` in sub repos. After the latest update the path names which allow me to differentiate between which is which is gone. So for all monolithic project structures this is now not usable 😢 

![error](https://user-images.githubusercontent.com/17417414/33278918-372b52c8-d39d-11e7-8669-e1b7c3b5a5e7.png)

**Preferred solution**
`npm run server wizer/packages/app`
`npm run server wizer/packages/dashboard`
`npm run server wizer/packages/website`

**Comment by lkytal** [comment]
I've noticed this problem. I made this modification because I don't want additional information messed up the interface, and to encourage using multi workspace instead of using subfolder. However, I'm already in process to display some combined information contained both workspace and path.

**Comment by lkytal** [comment]
Tentative information of path is provided in 3.3.1.

**Comment by nealoke** [comment]
Yep thanks for this!
