### ISSUE TITLE
VS code tasks don't show up if .vscode is excluded from project view.

### ISSUE THREAD

**Issue by haugerbr** [lkytal/quickTask#25]
If I want to hide the .vscode folder since it really shoudn't be shown in the explorer view, it causes the extension to not find the tasks.json file and those tasks do not show up in the view. Is there any way for the extension to still find the tasks with the folder or file hidden from the explorer view?

**Comment by RUSshy** [comment]
I have same problem, this make this extention unusable

**Comment by lkytal** [comment]
I've noticed that VS Code won't search within hidden folders, however, I haven't found the document of how to change this behavior yet, I may find some workaround later.

**Comment by haugerbr** [comment]
@RUSshy @lkytal I wrote a quick extension that just binds vscodes native workbench.action.tasks.runTask to a status bar item. This should show all the tasks available even when .vscode is hidden and also has the benefit of showing recent tasks at the top.

**Comment by haugerbr** [comment]
@Ikytal I think you have some benefits scanning for tasks and customizing the view. Mine will be at the mercy of what vscode does with the task runner in the future. I just wanted it mainly so I could hide vs code and have recently used tasks at the top.

**Comment by haugerbr** [comment]
@RUSshy @lkytal It's published

https://marketplace.visualstudio.com/items?itemName=haugerbr.project-tasks

**Comment by haugerbr** [comment]
@lkytal I see what you mean now. If that can work and solves the problem of hidden folders not contributing tasks then I think I'll switch back to using yours. Especially if there is a way to order and hide tasks in the dropdown menu.

**Comment by lkytal** [comment]
Should be fixed in version 3.5.0.
