### ISSUE TITLE
Please add typescript gulp files

### ISSUE THREAD

**Issue by simpert** [lkytal/quickTask#28]
*Gulp* has built-in support for typescript.

If you have `ts-node` installed eg: `npm i -D ts-node` then you can include a `gulpfile.ts` file and simply run the `gulp` command.

`gulp` will automatically register with `ts-node` to transpile in memory and execute the resulting javascript. I think it does it like so `gulp --require ts-node/register`

I use `typescript` for my gulp files as it gives me great intellisense and library discovery. Also, everything in my project is typescript so the uniformity is nice. I allready had `ts-node` since `mocha` requires it to use `typescript`.

I really like your extension and use for my vs tasks and npm scripts.

Please allow `.ts` files for gulp file globs to allow typescript.

**Comment by lkytal** [comment]
Hi, I've added tentative support to `gulpfile.ts`, let me if it works as intended.

**Comment by simpert** [comment]
Seems to work great. Thank you so much.
________________________________
