### ISSUE TITLE
Task is running with wrong path in 3.5.2, when gulpfile.js in subdirectory

### ISSUE THREAD

**Issue by Dimox** [lkytal/quickTask#29]
Hi,

I have the following structure of my project:

```
/project/
  /_dev/
    ...
    node_modules
    gulpfile.js
```

In quickTask 3.5.1 all was fine. But in 3.5.2 terminal is opening project root directory and trying to run a task, and I'm getting the following error:

```
[10:32:26] Local gulp not found in "path_to/project"
[10:32:26] Try running: npm install gulp
```
Expected result: terminal must open `/project/_dev/` directory instead of `/project/` and then run a task.

**Comment by lkytal** [comment]
Shall be fixed in 3.5.3.
