### ISSUE TITLE
Default task sample ?

### ISSUE THREAD

**Issue by freMea** [lkytal/quickTask#4]
Hi,

Please give an example of how to set multiple tasks in 

```
// You can add default tasks that will show up in task list.
"quicktask.defaultTasks": [],
```

It would be great too if we could add keybinding for any custom task the user create.

Thanks

**Comment by lkytal** [comment]
Please first update to 2.4.1 which fixed up the default tasks support. "defaultTasks" should be an array, keybinding for custom tasks will take some time to complete.

**Comment by freMea** [comment]
Ok but how do I set them? I would like to for example create a default task that will run a terminal in current folder:
`browser-sync start --server --files "*.css, *html, *.js"`
and give it a custom name:
`BrowserSync start [default config]`
Can I do that?

**Comment by lkytal** [comment]
You can just set is as ["browser-sync start --server --files \"*.css, *html, *.js\""], this command will always show up.

**Comment by isometriq** [comment]
Would it be complicated to support an an array of objects like these?
```
{
    "taskName": "chrome",
    "command": "cmd /C start chrome -incognito \"http:\/\/localhost:3000\/dist\/examples\"",
    "args": [], // maybe?
}
```
Something similar as possible to tasks.json structure

**Comment by lkytal** [comment]
An object like this may make things more confusing... I'm considering support it someday, maybe.

**Comment by isometriq** [comment]
Dunno, it's a sample of the same syntax as the `tasks.json`.
