### ISSUE TITLE
Not working for Gulp if gulpfile named gulpfile.babel.js

### ISSUE THREAD

**Issue by Grawl** [lkytal/quickTask#6]

**Comment by lkytal** [comment]
You may modify "quicktask.gulpGlob" config to include any gulp file you want.

**Comment by Grawl** [comment]
Thank you, looks like it's working. Maybe this issue is a reason to add CoffeeScript, TypeScript, Babel and another versions of gulpfiles? I think `gulpfile*` as default will be a good choice (if quickTask can read TypeScript and CoffeeScript of cource).

**Comment by lkytal** [comment]
Well, currently I won't expand gulp file to all kind, that might be confusing to new users.
