### ISSUE TITLE
[Feature Request] Respect `hide` setting

### ISSUE THREAD

**Issue by lonix1** [lkytal/quickTask#65]
The `tasks.json` has this [setting](https://code.visualstudio.com/docs/terminal):
````json
"hide": true|false,
````

When `true`, a task is not shown in the "task run" list, so it is only used as a dependency of other tasks.

It would be nice if the extension respected that setting - so if it's `true`, then the task would not appear in the quick pick list.

**Comment by lkytal** [comment]
Fixed in version 3.5.8
