### ISSUE TITLE
Feature Requests: Simpler status bar progress

### ISSUE THREAD

**Issue by ProLoser** [lkytal/quickTask#7]
First I must say I like your fork better than Task Manager extension. That said, I feel like you should give some credit because this is an obvious fork. That said, here are some suggestions:

Instead of adding full sentences to the status bar when you trigger a task, reuse the status bar button for displaying a concise status. You can use progress spinners instead of verbose sentences. Instead of  `gulp test task started` you can do `🔄 gulp test` with an animation or something similar (see images).

quickTask (long, text-based, causes lots of movement and UI dissorientation):
![hz5nvfoorq](https://cloud.githubusercontent.com/assets/67395/26175672/450f836a-3b08-11e7-9c50-d04101253e23.gif)

Quokka (concise, animated, icon-based):
![m8dft1xkhe](https://cloud.githubusercontent.com/assets/67395/26175680/4982855a-3b08-11e7-9046-8c045f58e223.gif)

**Comment by lkytal** [comment]
Thanks for your advice, I'll consider replace it by animated icon in recents.

I've already refered original _task master_ extension in acknowledgment section, and, although this extension started by fork, I've rewritten the hole code for better performance, not a single line from _task master_ remains now, lol.

**Comment by ProLoser** [comment]
I would think then out of respect and support of open source you could at least acknowledge it as an original starting point or inspiration in your description so that it doesn't seem deliberately undermining. Considering it has more installs but yours is in fact faster, mentioning the rewrite for efficiency might be good for marketing.

Not critical, just random thoughts.

**Comment by lkytal** [comment]
Well, I may explain more clearly in acknowledgment of how I start from it.

**Comment by lkytal** [comment]
Should reuse the status bar icon now, in version 2.7.0
