### ISSUE TITLE
Does not find any tasks from NPM or gulp

### ISSUE THREAD

**Issue by nealoke** [lkytal/quickTask#9]
Hi I'm having trouble using this plugin, it does not show any tasks from `NPM` or `gulp`. Could it be because it has more then one `gulpfile` and `package.json` files located in a sub folder?

**Comment by lkytal** [comment]
QuickTask does not support  sub folder by default. Please update to version 2.9.0 first, then enable option 'searchTaskFileInSubdirectories'.

**Comment by nealoke** [comment]
Great! The only thing now is that it is quite confusing which task is from what file

**Example**
![image](https://user-images.githubusercontent.com/17417414/28963029-e6c788f0-7907-11e7-9223-4119680a8523.png)


Might it be possible to add the folder it is selected from like `npm build (folder/folder`)?

**Comment by lkytal** [comment]
I've notice this and I'm working on it, maybe in next version.

**Comment by lkytal** [comment]
Version 2.9.1 should list folder in description.
